// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-enS2wsxnHg_hn6W94qYiY8i2Vi05KOU',
    appId: '1:315730159319:web:5d42f13b22648d6e8ef292',
    messagingSenderId: '315730159319',
    projectId: 'ornimetrics',
    authDomain: 'ornimetrics.firebaseapp.com',
    databaseURL: 'https://ornimetrics-default-rtdb.firebaseio.com',
    storageBucket: 'ornimetrics.firebasestorage.app',
    measurementId: 'G-QMPZNBXCBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj6cUazoTE11sNsM8mXGJqAWnSPjc2SGM',
    appId: '1:315730159319:android:2470c4aa46fc2a728ef292',
    messagingSenderId: '315730159319',
    projectId: 'ornimetrics',
    databaseURL: 'https://ornimetrics-default-rtdb.firebaseio.com',
    storageBucket: 'ornimetrics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvwo04FNJvcUYxRfAQsO-5lRYmmyU9BwY',
    appId: '1:315730159319:ios:dabebf0666a48f2b8ef292',
    messagingSenderId: '315730159319',
    projectId: 'ornimetrics',
    databaseURL: 'https://ornimetrics-default-rtdb.firebaseio.com',
    storageBucket: 'ornimetrics.firebasestorage.app',
    iosBundleId: 'com.example.ornimetricsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvwo04FNJvcUYxRfAQsO-5lRYmmyU9BwY',
    appId: '1:315730159319:ios:dabebf0666a48f2b8ef292',
    messagingSenderId: '315730159319',
    projectId: 'ornimetrics',
    databaseURL: 'https://ornimetrics-default-rtdb.firebaseio.com',
    storageBucket: 'ornimetrics.firebasestorage.app',
    iosBundleId: 'com.example.ornimetricsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-enS2wsxnHg_hn6W94qYiY8i2Vi05KOU',
    appId: '1:315730159319:web:d62f07487c1622e98ef292',
    messagingSenderId: '315730159319',
    projectId: 'ornimetrics',
    authDomain: 'ornimetrics.firebaseapp.com',
    databaseURL: 'https://ornimetrics-default-rtdb.firebaseio.com',
    storageBucket: 'ornimetrics.firebasestorage.app',
    measurementId: 'G-JMPGW2FFZ9',
  );
}
